#version: "3"


#services:
  #web:
    #build: .
    #command: gunicorn -w 4 -b 0.0.0.0:8000 app.wsgi:app
    #volumes:
     # - ./app:/app
    #ports:
    #  - "8000:8000"
   # depends_on:
  #    - redis

 # redis:
#    image: "redis:alpine"


version: '3'

services:
  web:
    build: .
      #context: .
     # dockerfile: Docker-python/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./flask-app:/app
    environment:
      - FLASK_APP=app.wsgi:app
      - FLASK_ENV=development
    command: gunicorn -b 0.0.0.0:5000 -w 4 app.wsgi:app
    #depends_on:
     # - db

#  db:
 #   image: "sqlite:latest"
  #  volumes:
   #   - ./app:/app
